module.exports = {
    MESSAGE: 'MESSAGE',
    // Queues
    QUEUE_SUBSCRIBE: 'QUEUE_SUBSCRIBE',
    QUEUE_UPDATE: 'QUEUE_UPDATE',
    QUEUE_DELETED: 'QUEUE_DELETED',
    QUEUE_CLOSED: 'QUEUE_CLOSED',
    // Schedules
    QUEUE_SCHEDULE_CREATE: 'QUEUE_SCHEDULE_CREATE',
    QUEUE_SCHEDULE_UPDATE: 'QUEUE_SCHEDULE_UPDATE',
    QUEUE_SCHEDULE_DELETED: 'QUEUE_SCHEDULE_DELETED',
    // Holidays
    QUEUE_HOLIDAY_CREATE: 'QUEUE_HOLIDAY_CREATE',
    QUEUE_HOLIDAY_UPDATE: 'QUEUE_HOLIDAY_UPDATE',
    QUEUE_HOLIDAY_DELETED: 'QUEUE_HOLIDAY_DELETED',
    // Positions
    QUEUE_MEMBER_ENTRY: 'QUEUE_MEMBER_ENTRY',
    QUEUE_MEMBER_MOVE: 'QUEUE_MEMBER_MOVE',
    QUEUE_MEMBER_LEAVE: 'QUEUE_MEMBER_LEAVE',
    // Users
    USER_UPDATE: 'USER_UPDATE',
};
